/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xgame.framework.rpc;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-09-10")
public class W2L_ResourceSimpleSprite implements org.apache.thrift.TBase<W2L_ResourceSimpleSprite, W2L_ResourceSimpleSprite._Fields>, java.io.Serializable, Cloneable, Comparable<W2L_ResourceSimpleSprite> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("W2L_ResourceSimpleSprite");

  private static final org.apache.thrift.protocol.TField RESOURCE_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("resourceNum", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField UID_FIELD_DESC = new org.apache.thrift.protocol.TField("uid", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField USE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("useName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField USE_SPEED_FIELD_DESC = new org.apache.thrift.protocol.TField("useSpeed", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new W2L_ResourceSimpleSpriteStandardSchemeFactory());
    schemes.put(TupleScheme.class, new W2L_ResourceSimpleSpriteTupleSchemeFactory());
  }

  public long resourceNum; // required
  public long uid; // required
  public String useName; // required
  public int useSpeed; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESOURCE_NUM((short)1, "resourceNum"),
    UID((short)2, "uid"),
    USE_NAME((short)3, "useName"),
    USE_SPEED((short)4, "useSpeed");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESOURCE_NUM
          return RESOURCE_NUM;
        case 2: // UID
          return UID;
        case 3: // USE_NAME
          return USE_NAME;
        case 4: // USE_SPEED
          return USE_SPEED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RESOURCENUM_ISSET_ID = 0;
  private static final int __UID_ISSET_ID = 1;
  private static final int __USESPEED_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESOURCE_NUM, new org.apache.thrift.meta_data.FieldMetaData("resourceNum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.UID, new org.apache.thrift.meta_data.FieldMetaData("uid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.USE_NAME, new org.apache.thrift.meta_data.FieldMetaData("useName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USE_SPEED, new org.apache.thrift.meta_data.FieldMetaData("useSpeed", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(W2L_ResourceSimpleSprite.class, metaDataMap);
  }

  public W2L_ResourceSimpleSprite() {
  }

  public W2L_ResourceSimpleSprite(
    long resourceNum,
    long uid,
    String useName,
    int useSpeed)
  {
    this();
    this.resourceNum = resourceNum;
    setResourceNumIsSet(true);
    this.uid = uid;
    setUidIsSet(true);
    this.useName = useName;
    this.useSpeed = useSpeed;
    setUseSpeedIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public W2L_ResourceSimpleSprite(W2L_ResourceSimpleSprite other) {
    __isset_bitfield = other.__isset_bitfield;
    this.resourceNum = other.resourceNum;
    this.uid = other.uid;
    if (other.isSetUseName()) {
      this.useName = other.useName;
    }
    this.useSpeed = other.useSpeed;
  }

  public W2L_ResourceSimpleSprite deepCopy() {
    return new W2L_ResourceSimpleSprite(this);
  }

  @Override
  public void clear() {
    setResourceNumIsSet(false);
    this.resourceNum = 0;
    setUidIsSet(false);
    this.uid = 0;
    this.useName = null;
    setUseSpeedIsSet(false);
    this.useSpeed = 0;
  }

  public long getResourceNum() {
    return this.resourceNum;
  }

  public W2L_ResourceSimpleSprite setResourceNum(long resourceNum) {
    this.resourceNum = resourceNum;
    setResourceNumIsSet(true);
    return this;
  }

  public void unsetResourceNum() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RESOURCENUM_ISSET_ID);
  }

  /** Returns true if field resourceNum is set (has been assigned a value) and false otherwise */
  public boolean isSetResourceNum() {
    return EncodingUtils.testBit(__isset_bitfield, __RESOURCENUM_ISSET_ID);
  }

  public void setResourceNumIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RESOURCENUM_ISSET_ID, value);
  }

  public long getUid() {
    return this.uid;
  }

  public W2L_ResourceSimpleSprite setUid(long uid) {
    this.uid = uid;
    setUidIsSet(true);
    return this;
  }

  public void unsetUid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __UID_ISSET_ID);
  }

  /** Returns true if field uid is set (has been assigned a value) and false otherwise */
  public boolean isSetUid() {
    return EncodingUtils.testBit(__isset_bitfield, __UID_ISSET_ID);
  }

  public void setUidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __UID_ISSET_ID, value);
  }

  public String getUseName() {
    return this.useName;
  }

  public W2L_ResourceSimpleSprite setUseName(String useName) {
    this.useName = useName;
    return this;
  }

  public void unsetUseName() {
    this.useName = null;
  }

  /** Returns true if field useName is set (has been assigned a value) and false otherwise */
  public boolean isSetUseName() {
    return this.useName != null;
  }

  public void setUseNameIsSet(boolean value) {
    if (!value) {
      this.useName = null;
    }
  }

  public int getUseSpeed() {
    return this.useSpeed;
  }

  public W2L_ResourceSimpleSprite setUseSpeed(int useSpeed) {
    this.useSpeed = useSpeed;
    setUseSpeedIsSet(true);
    return this;
  }

  public void unsetUseSpeed() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __USESPEED_ISSET_ID);
  }

  /** Returns true if field useSpeed is set (has been assigned a value) and false otherwise */
  public boolean isSetUseSpeed() {
    return EncodingUtils.testBit(__isset_bitfield, __USESPEED_ISSET_ID);
  }

  public void setUseSpeedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __USESPEED_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESOURCE_NUM:
      if (value == null) {
        unsetResourceNum();
      } else {
        setResourceNum((Long)value);
      }
      break;

    case UID:
      if (value == null) {
        unsetUid();
      } else {
        setUid((Long)value);
      }
      break;

    case USE_NAME:
      if (value == null) {
        unsetUseName();
      } else {
        setUseName((String)value);
      }
      break;

    case USE_SPEED:
      if (value == null) {
        unsetUseSpeed();
      } else {
        setUseSpeed((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESOURCE_NUM:
      return getResourceNum();

    case UID:
      return getUid();

    case USE_NAME:
      return getUseName();

    case USE_SPEED:
      return getUseSpeed();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESOURCE_NUM:
      return isSetResourceNum();
    case UID:
      return isSetUid();
    case USE_NAME:
      return isSetUseName();
    case USE_SPEED:
      return isSetUseSpeed();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof W2L_ResourceSimpleSprite)
      return this.equals((W2L_ResourceSimpleSprite)that);
    return false;
  }

  public boolean equals(W2L_ResourceSimpleSprite that) {
    if (that == null)
      return false;

    boolean this_present_resourceNum = true;
    boolean that_present_resourceNum = true;
    if (this_present_resourceNum || that_present_resourceNum) {
      if (!(this_present_resourceNum && that_present_resourceNum))
        return false;
      if (this.resourceNum != that.resourceNum)
        return false;
    }

    boolean this_present_uid = true;
    boolean that_present_uid = true;
    if (this_present_uid || that_present_uid) {
      if (!(this_present_uid && that_present_uid))
        return false;
      if (this.uid != that.uid)
        return false;
    }

    boolean this_present_useName = true && this.isSetUseName();
    boolean that_present_useName = true && that.isSetUseName();
    if (this_present_useName || that_present_useName) {
      if (!(this_present_useName && that_present_useName))
        return false;
      if (!this.useName.equals(that.useName))
        return false;
    }

    boolean this_present_useSpeed = true;
    boolean that_present_useSpeed = true;
    if (this_present_useSpeed || that_present_useSpeed) {
      if (!(this_present_useSpeed && that_present_useSpeed))
        return false;
      if (this.useSpeed != that.useSpeed)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_resourceNum = true;
    list.add(present_resourceNum);
    if (present_resourceNum)
      list.add(resourceNum);

    boolean present_uid = true;
    list.add(present_uid);
    if (present_uid)
      list.add(uid);

    boolean present_useName = true && (isSetUseName());
    list.add(present_useName);
    if (present_useName)
      list.add(useName);

    boolean present_useSpeed = true;
    list.add(present_useSpeed);
    if (present_useSpeed)
      list.add(useSpeed);

    return list.hashCode();
  }

  @Override
  public int compareTo(W2L_ResourceSimpleSprite other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetResourceNum()).compareTo(other.isSetResourceNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResourceNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resourceNum, other.resourceNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUid()).compareTo(other.isSetUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uid, other.uid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUseName()).compareTo(other.isSetUseName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUseName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.useName, other.useName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUseSpeed()).compareTo(other.isSetUseSpeed());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUseSpeed()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.useSpeed, other.useSpeed);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("W2L_ResourceSimpleSprite(");
    boolean first = true;

    sb.append("resourceNum:");
    sb.append(this.resourceNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("uid:");
    sb.append(this.uid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("useName:");
    if (this.useName == null) {
      sb.append("null");
    } else {
      sb.append(this.useName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("useSpeed:");
    sb.append(this.useSpeed);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class W2L_ResourceSimpleSpriteStandardSchemeFactory implements SchemeFactory {
    public W2L_ResourceSimpleSpriteStandardScheme getScheme() {
      return new W2L_ResourceSimpleSpriteStandardScheme();
    }
  }

  private static class W2L_ResourceSimpleSpriteStandardScheme extends StandardScheme<W2L_ResourceSimpleSprite> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, W2L_ResourceSimpleSprite struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESOURCE_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.resourceNum = iprot.readI64();
              struct.setResourceNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // UID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.uid = iprot.readI64();
              struct.setUidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // USE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.useName = iprot.readString();
              struct.setUseNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // USE_SPEED
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.useSpeed = iprot.readI32();
              struct.setUseSpeedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, W2L_ResourceSimpleSprite struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(RESOURCE_NUM_FIELD_DESC);
      oprot.writeI64(struct.resourceNum);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(UID_FIELD_DESC);
      oprot.writeI64(struct.uid);
      oprot.writeFieldEnd();
      if (struct.useName != null) {
        oprot.writeFieldBegin(USE_NAME_FIELD_DESC);
        oprot.writeString(struct.useName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(USE_SPEED_FIELD_DESC);
      oprot.writeI32(struct.useSpeed);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class W2L_ResourceSimpleSpriteTupleSchemeFactory implements SchemeFactory {
    public W2L_ResourceSimpleSpriteTupleScheme getScheme() {
      return new W2L_ResourceSimpleSpriteTupleScheme();
    }
  }

  private static class W2L_ResourceSimpleSpriteTupleScheme extends TupleScheme<W2L_ResourceSimpleSprite> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, W2L_ResourceSimpleSprite struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetResourceNum()) {
        optionals.set(0);
      }
      if (struct.isSetUid()) {
        optionals.set(1);
      }
      if (struct.isSetUseName()) {
        optionals.set(2);
      }
      if (struct.isSetUseSpeed()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetResourceNum()) {
        oprot.writeI64(struct.resourceNum);
      }
      if (struct.isSetUid()) {
        oprot.writeI64(struct.uid);
      }
      if (struct.isSetUseName()) {
        oprot.writeString(struct.useName);
      }
      if (struct.isSetUseSpeed()) {
        oprot.writeI32(struct.useSpeed);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, W2L_ResourceSimpleSprite struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.resourceNum = iprot.readI64();
        struct.setResourceNumIsSet(true);
      }
      if (incoming.get(1)) {
        struct.uid = iprot.readI64();
        struct.setUidIsSet(true);
      }
      if (incoming.get(2)) {
        struct.useName = iprot.readString();
        struct.setUseNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.useSpeed = iprot.readI32();
        struct.setUseSpeedIsSet(true);
      }
    }
  }

}

